version: "3.3"
services:
  santiwebservice:
    image: santiwebservice:latest
    ports:
      - "8080:8080"
  
    
    networks:
      - santi
    depends_on:
      - mysqldb
    
 
  mysqldb:
    image: mysql:8
 
    networks:
      - santi
    environment:
      - MYSQL_ROOT_PASSWORD=535353@@
      - MYSQL_DATABASE=santi_informations 

networks:
  santi: 